calc/amortization/urls.py
from django.conf.urls import patterns, url

from amortization import views

urlpatterns = patterns('',
		    url(r'^$', views.browse, name='browse'),
		    url(r'^add$', views.add, name='add'),
		    url(r'^new$', views.new, name='new'),
		    url(r'^(?P<loan_id>\d+)/$', views.read, name='read'),
		        # ex: /loans/1/
		    )

calc/calc/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^loans/', include('amortization.urls', namespace='loans')),
    url(r'^admin/', include(admin.site.urls)),
)

calc/amortization/models.py
from django.db import models

class Loan(models.Model):
	title_text = models.CharField(max_length=500)
	principal = models.FloatField(default=1000000)
	number_of_months = models.IntegerField(default=12)
	annual_interest_rate = models.FloatField(default=0.03)

	def __str__(self):
		return self.title_text

calc/amortization/controllers.py
from amortization.models import Loan
import math

class Payment:
	def __init__(self, number, principal, interest, cumulative_principal, cumulative_interest, principal_balance):
		self.number = number
		self.principal = principal
		self.interest = interest
		self.cumulative_principal = cumulative_principal
		self.cumulative_interest = cumulative_interest
		self.principal_balance = principal_balance

class Schedule:
	def __init__(self, loan):
		self._loan = loan
		self.payments = []

		self.total_interest_paid = loan.principal*loan.annual_interest_rate
		self.total_repaid = loan.principal + self.total_interest_paid

		# linear amortization
		monthly_interest = math.floor(100*self.total_interest_paid/loan.number_of_months)/100
		monthly_principal =  math.floor(100*loan.principal/loan.number_of_months)/100
		cumulative_principal = 0.0
		cumulative_interest = 0.0
		principal_balance = loan.principal

		# months 1 through 11
		for number in range(loan.number_of_months - 1):
			cumulative_principal += monthly_principal
			cumulative_interest += monthly_interest
			principal_balance -= monthly_principal
			self.payments += [ Payment(
				number+1,
				monthly_principal,
				monthly_interest,
				cumulative_principal,
				cumulative_interest,
				math.ceil(100*principal_balance)/100) ]

		# last payment (month 12)
		self.payments += [ Payment(
			loan.number_of_months,
			math.ceil(100*principal_balance)/100,
			self.total_interest_paid - cumulative_interest,
			loan.principal,
			self.total_interest_paid,
			0.0) ]

calc/amortization/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

from amortization.models import Loan
from amortization.controllers import Schedule

def browse(request):
	all_loans = Loan.objects.all()
	return render(request, 'loans/browse.html', {'all_loans': all_loans})

def read(request, loan_id):
	loan = get_object_or_404(Loan, id=loan_id)
	s = Schedule(loan)
	return render(request, 'loans/read.html', {'schedule': Schedule(loan)})

def add(request):
	return render(request, 'loans/add.html', {})

def new(request):
	new_loan = Loan(
			title_text  = request.POST['title'],
			principal = request.POST['principal'],
			number_of_months = request.POST['months'],
			annual_interest_rate = request.POST['rate']
			)
	new_loan.save()
	return render(request, 'loans/new.html', {
		'title': new_loan.title_text,
		'principal': new_loan.principal,
		'months': new_loan.number_of_months,
		'rate': new_loan.annual_interest_rate
		})

# TODO: add 'Delete' (DELETE) and 'Edit' (PUT) handlers

calc/amortization/templates/loans/add.html
<h1>New Loan</h1>
<form action="{% url 'loans:new' %}" method="post">
	{% csrf_token %}
	<input type="text" name="title" id="1" value="your title" />
	<label for="1">Loan Name</label><br />

	<input type="number" name="principal" id="2" value="1000000" />
	<label for="2">Principal</label><br />

	<input type="number" name="months" id="3" step="1" value="12" />
	<label for="3">Number Of Months</label><br />

	<input type="number" name="rate" id="4"  value="0.03" />
	<label for="4">Annual Interest Rate</label><br />

	<input type="submit" value="Add" />
</form>

calc/amortization/templates/loans/browse.html
{% if all_loans %}
<li><a href="/loans/add">Add Loan</a></li>
<h1>All Loans</h1>
<ul>
	{% for loan in all_loans %}
	<li><a href="/loans/{{ loan.id }}/">{{ loan.title_text }}</a></li>
	{% endfor %}
</ul>
{% else %}
<p>No loans have been created yet.</p>
{% endif %}

calc/amortization/templates/loans/new.html
<h1>Successfully added new loan "{{title}}"</h1>
<ul>
	<li>Title: {{title}}</li>
	<li>Title: {{principal}}</li>
	<li>Title: {{months}}</li>
	<li>Title: {{rate}}</li>
</ul>

<li><a href="/loans/">All Loans</a></li>

calc/amortization/templates/loans/read.html
<h1>{{ schedule.title_text }}</h1>
<ul>
	<li>Total Repaid: ${{ schedule.total_repaid }}</li>
	<li>Total Interest Paid: ${{ schedule.total_interest_paid }}</li>
	<table>
		<tr>
			<th>Number</th>
			<th>Principal</th>
			<th>Interest</th>
			<th>Cumulative Principal</th>
			<th>Cumulative Interest</th>
			<th>Principal Balance</th>

				{% for payment in schedule.payments %}
				<tr>
					<td>{{payment.number}}</td>
					<td>{{payment.principal}}</td>
					<td>{{payment.interest}}</td>
					<td>{{payment.cumulative_principal}}</td>
					<td>{{payment.cumulative_interest}}</td>
					<td>{{payment.principal_balance}}</td>
				</tr>
				{% endfor %}

		</tr>
	</table>
</ul>